const restObj = [
  {
    data: {
      type: "F",
      id: "712883",
      avgRating: '3.8',
      name: "Pizza Pasta Wala",
      uuid: "cae43d3e-0437-48de-8ffa-def3a5ed3937",
      city: "81",
      area: "Sector 15_FBD",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "4371ea20a925a4be398232931ff0e320",
      cuisines: [
        "Pizzas",
        "Pastas",
        "Burgers",
        "Fast Food",
        "Chinese",
        "Cafe",
        "Beverages",
      ],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 42,
      minDeliveryTime: 42,
      maxDeliveryTime: 42,
      slaString: "42 MINS",
      lastMileTravel: 3,
      slugs: {
        restaurant: "pizza-pasta-wala-sector-15_fbd-sector-15_fbd",
        city: "faridabad",
      },
      cityState: "81",
      address:
        "FCA 499 A, CHAWLA COLONY  BALLABGARH KALI MANDIR, Fatehpur  Biloch(58), Ballabgarh, Faridabad,  Haryana - 121004",
      locality: "Chawla Colony",
      parentId: 425630,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 4200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 4200,
        message: "",
        title: "Delivery Charge",
        amount: "4200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7067501~p=1~eid=00000189-0fb1-1f65-22b5-31bd00e20143~srvts=1688185413477",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3 kms",
      hasSurge: false,
      sla: {
        restaurantId: "712883",
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "--",
      totalRatings: 0,
      new: true,
    },
  },
  {
    data: {
      type: "F",
      id: "712884",
      avgRating: '4.1',
      name: "Pizza Wala",
      uuid: "cae43d3e-0437-48de-8ffa-def3a5ed3937",
      city: "81",
      area: "Sector 15_FBD",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "4371ea20a925a4be398232931ff0e320",
      cuisines: [
        "Pizzas",
        "Pastas",
        "Burgers",
        "Fast Food",
        "Chinese",
        "Cafe",
        "Beverages",
      ],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 42,
      minDeliveryTime: 42,
      maxDeliveryTime: 42,
      slaString: "42 MINS",
      lastMileTravel: 3,
    },
  },
  {
    data: {
      type: "F",
      id: "7124",
      avgRating: '4.8',
      name: "Pizza H",
      cloudinaryImageId: "4371ea20a925a4be398232931ff0e320",
      cuisines: [
        "Pizzas",
        "Pastas",
        "Burgers",
        "Fast Food",
        "Chinese",
        "Cafe",
        "Beverages",
      ],
      costForTwo: 40000
    },
  },
];

export default restObj;
